# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: La Bodega del Lupulo
email: info@labodegadellupulo.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog

# CHANGE THIS BACK TO URL!!!
url: "https://labodegadellupulo.com" # the base hostname & protocol for your site, e.g. http://example.com

# url: "http://localhost:3000/" # the base hostname & protocol for your site, e.g. http://example.com
baseimageurl: "https://labodegadellupulo.s3.eu-west-3.amazonaws.com/images/birras/"
facebook: https://www.facebook.com/LaBodegaDelLupulo/
instagram: http://instagram.com/la_bodega_del_lupulo
github_username:  jekyll 
construccion: "false"
ngrok_url: https://9d955554.ngrok.io 
catalogo: https://labodegadellupulo.s3.eu-west-3.amazonaws.com/catalogo/CatalogoLaBodegaDelLupulo.pdf
localhost: http://localhost:3000
development: true

# Build settings
markdown: kramdown
#theme: jekyll-theme-slate
plugins:
  - jekyll-feedsmall.jpg
  - jekyll-money
  - jekyll-minifier
  - jekyll-sitemap
  - jekyll-paginate

sass:
  style: compressed


collections:
  birras:
    output: true
    permalink: /cervezas/:title.html
  posts:
    title: LupuloBlog
    intro:
    output: true

permalink: /:title/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
keep_files: [assets]   
exclude:
  - package.json
  - node_modules
  - gulpfile.js
  - assets